// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ozfasfotlkjxcfuzohix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im96ZmFzZm90bGtqeGNmdXpvaGl4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5Mzg3NDEsImV4cCI6MjA2NDUxNDc0MX0.lMzyEZ2u7dV6VeWZ1xhRXxMPcHovZXI_B9dv4lrC_M4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);